In [125]:
import numpy as np
from numpy import random as rd
from pykrx import stock
import scipy as sp
#아래 티커는 각각 kodex레버리지 / KODEX 인버스 / kosef미국달러선물 / KODEX 모멘텀PLUS
ETF_ticker = ["002810", "003920", "004380", "011280", "016580", "007340", "000370", "001510", "033270", "004710", "001500"]
N = len(ETF_ticker)
stocks_data = []
srt = "20010101"
end = "20191231"
for i in range(0, N):
    stocks_data.append(stock.get_market_ohlcv_by_date(srt, end, ETF_ticker[i])["종가"])#룩백윈도우는 300일


In [126]:
import pandas as pd

In [161]:
from scipy import optimize

In [142]:
data = pd.DataFrame(np.asarray(stocks_data).T, columns=ETF_ticker, dtype=np.int32)

In [143]:
data

002810  003920  004380  011280  016580  007340  000370  001510  033270  \
0       1507  252000     727     335    2612    3678   13502    2081    2110   
1       1541  254000     731     326    2622    3678   13502    2150    2230   
2       1591  252000     757     350    2602    3694   14195    2467    2430   
3       1558  253000     746     353    2492    3678   16110    2833    2385   
4       1541  255000     755     357    2652    3757   16538    3255    2350   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
4690   15709  425000   11500    4130   15800   29450    2850     603   18500   
4691   15852  436000   11350    4100   15450   29500    2860     600   18300   
4692   15900  433000   11500    4290   15500   29600    2840     607   18500   
4693   16050  431000   11700    4355   15400   29350    2820     607   18250   
4694   15900  439500   11600    4250   15450   29350    2825     607   18350   

      004710  001500  
0       5781    2468  
1       6641    2488  
2       7620    2859  
3       7650    3159  
4       7650    3135  
...      ...     ...  
4690    8750   10350  
4691    8240   10350  
4692    8750   10500  
4693    8800   10100  
4694    8940   10050  

[4695 rows x 11 columns]

In [144]:
for i in range(1, data.shape[0]):
    data_.iloc[i,:] = (data.iloc[i,:]-data.iloc[i-1,:])/data.iloc[i-1,:]

In [145]:
data_.iloc[0,:] = np.nan

In [146]:
data_.head(20)

002810    003920    004380    011280    016580    007340    000370  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1   0.022561  0.007937  0.005502 -0.026866  0.003828  0.000000  0.000000   
2   0.032446 -0.007874  0.035568  0.073620 -0.007628  0.004350  0.051326   
3  -0.020742  0.003968 -0.014531  0.008571 -0.042275 -0.004331  0.134907   
4  -0.010911  0.007905  0.012064  0.011331  0.064205  0.021479  0.026567   
5   0.022064 -0.001961  0.017219  0.019608 -0.005656  0.000000 -0.061797   
6   0.010159 -0.017682  0.042969 -0.024725 -0.051195 -0.016769 -0.150039   
7  -0.026398 -0.004000 -0.012484 -0.008451  0.027978 -0.006497  0.116394   
8   0.016785  0.016064  0.075853  0.017045  0.011664 -0.006267 -0.004551   
9   0.010159  0.005929  0.000000  0.013966  0.076864  0.000000 -0.011190   
10 -0.047140 -0.001965 -0.051704 -0.027548 -0.039258  0.000000  0.025117   
11 -0.005937  0.000000 -0.024783 -0.022663  0.148588  0.006307 -0.048936   
12 -0.019244  0.000000  0.005083  0.000000 -0.084088 -0.008447 -0.018685   
13  0.005413 -0.015748 -0.018963  0.000000 -0.038842  0.000000  0.004760   
14  0.014132  0.000000  0.019330  0.011594  0.003674  0.008519  0.059220   
15 -0.007963  0.004000 -0.025284 -0.002865 -0.016471 -0.019346 -0.031309   
16 -0.011371 -0.003984  0.038911  0.014368  0.005582  0.017505  0.000000   
17  0.034506  0.000000  0.033708  0.025496  0.037010 -0.006281  0.003428   
18 -0.014388  0.000000 -0.028986 -0.002762 -0.007138  0.000000  0.056404   
19 -0.013935 -0.004000  0.034826  0.036011 -0.007189  0.000000 -0.035969   

      001510    033270    004710    001500  
0        NaN       NaN       NaN       NaN  
1   0.033157  0.056872  0.148763  0.008104  
2   0.147442  0.089686  0.147418  0.149116  
3   0.148358 -0.018519  0.003937  0.104932  
4   0.148959 -0.014675  0.000000 -0.007597  
5   0.084178  0.034043  0.054118 -0.009888  
6  -0.147917 -0.028807 -0.095486 -0.067977  
7   0.148653  0.118644  0.016041  0.145869  
8   0.032716 -0.028409  0.000000 -0.040121  
9   0.053827  0.005848  0.032249 -0.019485  
10  0.090716 -0.023256 -0.023268  0.049679  
11 -0.037805  0.071429 -0.063571 -0.047328  
12 -0.007858 -0.022222  0.008575  0.000000  
13 -0.034747 -0.011364  0.008360 -0.012500  
14  0.023028  0.022989  0.108207  0.025316  
15 -0.067788  0.059925 -0.052498 -0.037037  
16  0.017485  0.106007  0.146815  0.000000  
17 -0.006819  0.000000  0.003618  0.010191  
18  0.095303 -0.009585 -0.031163  0.053043  
19 -0.062187 -0.038710 -0.018003 -0.034611

In [190]:
"""#raw data 는 python 2d python array로 가정하지말고 DataFrame으로...

def seq_optima(data):#param ex : window type , w optima TF, -> 일단 픽스
    while True: #sliding window, MaxSR
        #window length를 설정해주고
        #window length와 데이터 전체 길이가 유효한 값인지 체크.
        #window Len = REbalance Freq = Test Len ????
        win_len = 1
        #window length에 맞는 cov mat 생성
        var_cov_mat = None
        #생성된 cov mat에 따라 최적 w 를 찾는다.
        w = w_optima(data, win_len)
        
        #수익률을 계산한다.
        
        if 수익률이 향상되었는가?
            #반복문 한번더, 5일씩 증가할건가? 1일씩 증가할건가?
            win_len += 1
        elif 수익률이 떨어졌는가?
            #여기서 그만.
            break
            #길이와 수익률을 로깅.
            
    return win_len"""

           
def eq_constraint(w): # w값들의 합이 1이 되어야 한다.
    summation = 0
    for i in w:
        summation += i
    return summation -1

def flarray(w): #샤프지수가 최대가 되게하는 목적함수
    ret_exd = np.cumprod(ret) - 0.015
    return -(np.dot(np.transpose(ret_exd.iloc[-1]), w) / (np.dot(np.dot(np.transpose(w), var_cov_mat), w))**(1/2))

def get_W_Max_Sharp(var_cov_mat):
    return sp.optimize.fmin_slsqp(flarray, [1/N for i in range(N)], bounds=[(0,1) for i in range(N)], eqcons=[eq_constraint])

In [172]:
rf = 0.015

In [211]:
var_cov_mat = np.identity(N)
for i in range(0, N):
    for j in range(0, N):
        var_cov_mat[i][j] = np.cov(ret.iloc[1:,i], ret.iloc[1:,j])[0,1]

In [224]:
np.cov(ret.iloc[1:,1], ret.iloc[1:,10])

array([[0.00046663, 0.00011337],
       [0.00011337, 0.00078483]])

In [213]:
var_cov_mat

array([[4.79922485e-04, 5.48249896e-05, 1.05658364e-04, 1.20898590e-04,
        8.14110679e-05, 5.13193908e-05, 1.44185064e-04, 1.62475984e-04,
        1.23065600e-04, 1.88079353e-04, 1.50805652e-04],
       [5.48249896e-05, 4.66633372e-04, 4.56347388e-05, 7.71164038e-05,
        4.98071822e-05, 5.73152350e-05, 1.09319310e-04, 1.21075247e-04,
        7.93454509e-05, 1.26746934e-04, 1.13373263e-04],
       [1.05658364e-04, 4.56347388e-05, 8.18791749e-04, 1.41222466e-04,
        9.08698815e-05, 6.55351805e-05, 1.39217470e-04, 1.80619787e-04,
        1.22744377e-04, 2.26053270e-04, 1.55712255e-04],
       [1.20898590e-04, 7.71164038e-05, 1.41222466e-04, 6.94828602e-04,
        1.08150399e-04, 6.53813248e-05, 1.78981059e-04, 2.33203674e-04,
        1.50064053e-04, 2.49435580e-04, 2.05084038e-04],
       [8.14110679e-05, 4.98071822e-05, 9.08698815e-05, 1.08150399e-04,
        5.40604189e-04, 5.68063953e-05, 9.97769087e-05, 1.27127144e-04,
        1.85922158e-04, 1.36188911e-04, 1.08835086e-

In [195]:
w = [1/N for i in range(N)]
np.dot(np.transpose(np.cumprod(ret).iloc[-1]), w) / (np.dot(np.dot(np.transpose(w), var_cov_mat), w))**(1/2)

nan

In [185]:
np.cumprod(ret)

002810    003920     004380     011280    016580    007340    000370  \
0           NaN       NaN        NaN        NaN       NaN       NaN       NaN   
1      1.022561  1.007937   1.005502   0.973134  1.003828  1.000000  1.000000   
2      1.055740  1.000000   1.041265   1.044776  0.996172  1.004350  1.051326   
3      1.033842  1.003968   1.026135   1.053731  0.954058  1.000000  1.193157   
4      1.022561  1.011905   1.038514   1.065672  1.015314  1.021479  1.224856   
...         ...       ...        ...        ...       ...       ...       ...   
4690  10.424021  1.686508  15.818432  12.328358  6.049005  8.007069  0.211080   
4691  10.518912  1.730159  15.612105  12.238806  5.915008  8.020663  0.211820   
4692  10.550763  1.718254  15.818432  12.805970  5.934150  8.047852  0.210339   
4693  10.650299  1.710317  16.093535  13.000000  5.895865  7.979880  0.208858   
4694  10.550763  1.744048  15.955983  12.686567  5.915008  7.979880  0.209228   

        001510    033270    004710    001500  
0          NaN       NaN       NaN       NaN  
1     1.033157  1.056872  1.148763  1.008104  
2     1.185488  1.151659  1.318111  1.158428  
3     1.361365  1.130332  1.323300  1.279984  
4     1.564152  1.113744  1.323300  1.270259  
...        ...       ...       ...       ...  
4690  0.289765  8.767773  1.513579  4.193679  
4691  0.288323  8.672986  1.425359  4.193679  
4692  0.291687  8.767773  1.513579  4.254457  
4693  0.291687  8.649289  1.522228  4.092382  
4694  0.291687  8.696682  1.546445  4.072123  

[4695 rows x 11 columns]

In [177]:
np.cumprod(ret)

002810    003920     004380     011280    016580    007340    000370  \
0          NaN       NaN        NaN        NaN       NaN       NaN       NaN   
1     0.022561  0.007937   0.005502  -0.026866  0.003828  0.000000  0.000000   
2     0.055740  0.000000   0.041265   0.044776 -0.003828  0.004350  0.051326   
3     0.033842  0.003968   0.026135   0.053731 -0.045942  0.000000  0.193157   
4     0.022561  0.011905   0.038514   0.065672  0.015314  0.021479  0.224856   
...        ...       ...        ...        ...       ...       ...       ...   
4690  9.424021  0.686508  14.818432  11.328358  5.049005  7.007069 -0.788920   
4691  9.518912  0.730159  14.612105  11.238806  4.915008  7.020663 -0.788180   
4692  9.550763  0.718254  14.818432  11.805970  4.934150  7.047852 -0.789661   
4693  9.650299  0.710317  15.093535  12.000000  4.895865  6.979880 -0.791142   
4694  9.550763  0.744048  14.955983  11.686567  4.915008  6.979880 -0.790772   

        001510    033270    004710    001500  
0          NaN       NaN       NaN       NaN  
1     0.033157  0.056872  0.148763  0.008104  
2     0.185488  0.151659  0.318111  0.158428  
3     0.361365  0.130332  0.323300  0.279984  
4     0.564152  0.113744  0.323300  0.270259  
...        ...       ...       ...       ...  
4690 -0.710235  7.767773  0.513579  3.193679  
4691 -0.711677  7.672986  0.425359  3.193679  
4692 -0.708313  7.767773  0.513579  3.254457  
4693 -0.708313  7.649289  0.522228  3.092382  
4694 -0.708313  7.696682  0.546445  3.072123  

[4695 rows x 11 columns]

In [173]:
ret_exd = []
ret_exd.append(float(np.cumprod(ret[:,i])[-1:] - rf))

TypeError: '(slice(None, None, None), 4694)' is an invalid key

In [59]:
data.columns

Index(['002810', '003920', '004380', '011280', '016580', '007340', '000370',
       '001510', '033270', '004710', '001500'],
      dtype='object')

In [215]:
def a(data, day, beforehand):
    data_ = data.iloc[day-beforehand:day]
    ret = pd.DataFrame(np.nan, index=np.arange(data.shape[0]), columns=data.columns)

    for i in range(1, len(stocks_data[0])):
        ret.iloc[i] = data.iloc[i]/data.iloc[i-1]
    

    for i in range(0, N):
        for j in range(0, N):
            var_cov_mat[i][j] = np.cov(ret.iloc[1:,i], ret.iloc[1:,j])[0,1]
    return get_W_Max_Sharp(var_cov_mat)
 
kkkk =a(data, 100, 30)


Optimization terminated successfully.    (Exit mode 0)
            Current function value: -803.7172378958029
            Iterations: 17
            Function evaluations: 229
            Gradient evaluations: 16


In [220]:
np.round(kkkk, 2)

array([0.24, 0.  , 0.25, 0.19, 0.04, 0.23, 0.  , 0.  , 0.05, 0.  , 0.  ])

In [159]:
ret = pd.DataFrame(np.nan, index=np.arange(data.shape[0]), columns=data.columns)

for i in range(1, len(stocks_data[0])):
    ret.iloc[i] = data.iloc[i]/data.iloc[i-1]
ret.iloc[:,0]  

0            NaN
1       1.022561
2       1.032446
3       0.979258
4       0.989089
          ...   
4690    1.009187
4691    1.009103
4692    1.003028
4693    1.009434
4694    0.990654
Name: 002810, Length: 4695, dtype: float64

In [156]:
data.iloc[:,1]

0       252000
1       254000
2       252000
3       253000
4       255000
         ...  
4690    425000
4691    436000
4692    433000
4693    431000
4694    439500
Name: 003920, Length: 4695, dtype: int32

In [ ]:
ret = pd.DataFrame(np.nan,index=np.arange(len(stocks_data[0])), columns=ETF_ticker)
for stock, idx in zip(ETF_ticker, range(0,N)):
    for i in range(1, len(stocks_data[0])):
        ret[stock].iloc[i] =  stocks_data[idx][i]/stocks_data[idx][i-1] 
        
retArr = []
for stock in ETF_ticker:
    retArr.append( ret[stock].iloc[1:] )# 0일 수익률은 nan 값이라서 날짜 체크할때 하루 밀리는거 조심할것.