In [8]:
# import csv data from pykrx
from pykrx import stock
srt = "20050101"
end = "20191231"
stockCode_leverage = "122630"
stockCode_inverse_f = "252670"
df_lev = stock.get_market_ohlcv_by_date(srt, end, stockCode_leverage)
df_inv = stock.get_market_ohlcv_by_date(srt, end, stockCode_inverse_f)

In [10]:
#data check
df_lev

시가     고가     저가     종가       거래량
날짜                                              
2010-02-22  10010  10275  10010  10165    125001
2010-02-23  10165  10215  10025  10165    261358
2010-02-24  10060  10060   9865   9935    465118
2010-02-25  10050  10050   9545   9605    971853
2010-02-26   9655   9745   9585   9675    483447
...           ...    ...    ...    ...       ...
2019-12-23  14255  14270  14050  14125  10422755
2019-12-24  14145  14165  13925  13930   8808411
2019-12-26  13940  14125  13845  14045   9833293
2019-12-27  14175  14700  14135  14485  25871608
2019-12-30  14470  14555  14400  14425   7844724

[2432 rows x 5 columns]

In [11]:
df_inv

시가     고가    저가    종가       거래량
날짜                                           
2016-09-22  9835   9845  9720  9815   7849515
2016-09-23  9755   9840  9755  9820   9775392
2016-09-26  9840   9910  9735  9875  10065403
2016-09-27  9975  10040  9705  9745  15822705
2016-09-28  9765   9820  9745  9805   9475753
...          ...    ...   ...   ...       ...
2019-12-23  6190   6285  6190  6245  16905545
2019-12-24  6230   6340  6230  6335  19492646
2019-12-26  6330   6375  6290  6295  16231126
2019-12-27  6215   6255  5985  6090  31811394
2019-12-30  6080   6125  6055  6115  11515679

[803 rows x 5 columns]

In [12]:
close_lev = df_lev["종가"]
close_inv = df_inv["종가"]

In [156]:
import numpy as np
covmat = np.cov(close_lev[-500:], close_inv[-500:]) # look back window = 500
covmat

array([[ 4300773.32775551, -1562999.46392786],
       [-1562999.46392786,   626087.8256513 ]])

In [17]:
close_lev[-500:]

날짜
2017-12-14    17610
2017-12-15    17520
2017-12-18    17585
2017-12-19    17585
2017-12-20    17520
              ...  
2019-12-23    14125
2019-12-24    13930
2019-12-26    14045
2019-12-27    14485
2019-12-30    14425
Name: 종가, Length: 500, dtype: int32

In [44]:
covmat = np.cov(close_lev[-500:], close_inv[-500:]) / ( np.std(close_lev[-500:]) * np.std(close_inv[-500:]))
covmat

array([[ 2.62618373, -0.95441528],
       [-0.95441528,  0.38230837]])

In [ ]:
#to do
#1. 레버리지 - 인버스 단순 리스크패러티(inverse volatility)의 퍼포먼스
#2. 레버리지 - 인버스 공분산 고려한 ERC의 퍼포먼스

## to do to do
## 1. 

In [159]:
w = [0.5, 0.5]
wT = np.transpose(w)
np.dot(np.dot(wT,covmat),w)
sigma_w = np.dot(np.dot(wT,covmat),w)# = sigma(w)
sigma_w

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [82]:
a = ([1,2],[3,4])
b = ([1,0],[0,1])
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [81]:
a = np.asarray(close_lev[-500:])
b = np.asarray(close_inv[-500:])
cc = np.column_stack([a,b])

In [148]:
import numpy.random as rd
#np.round(rd.rand(1),2)
rd.rand(1)

array([0.6803643])

In [138]:
np.sum([1,2,3,4,5])

15

In [145]:
for i in range(0, 10):
        ww.append(rd.rand(0,1))
ww

NameError: name 'ww' is not defined

In [147]:
rd.rand(0,1)

array([], shape=(0, 1), dtype=float64)